name: Mayhem

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MUTATE: mutate.mayhemfile
  INCREMENTAL-PARSE: incremental-parse.mayhemfile
  PRINT-VALID-MODULE: print-valid-module.mayhemfile
  PRINT: print.mayhemfile
  ROUNDTRIP-VALID-MODULE: roundtrip-valid-module.mayhemfile
  ROUNDTRIP: roundtrip.mayhemfile
  TEXT-LEXER: text-lexer.mayhemfile
  TEXT-PARSER: text-parser.mayhemfile
  VALIDATE-ENSURE-TERMINATION: validate-ensure-termination.mayhemfile
  VALIDATE-VALID-MODULE: validate-valid-module.mayhemfile
  VALIDATE: validate.mayhemfile

jobs:
  build:
    name: ${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Start MUTATE analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.MUTATE }} --duration 300
          sarif-output: sarif

      - name: Start INCREMENTAL-PARSE analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.INCREMENTAL-PARSE }} --duration 300
          sarif-output: sarif

      - name: Start PRINT-VALID-MODULE analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.PRINT-VALID-MODULE }} --duration 300
          sarif-output: sarif

      - name: Start PRINT analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.PRINT }} --duration 300
          sarif-output: sarif

      - name: Start ROUNDTRIP-VALID-MODULE analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.ROUNDTRIP-VALID-MODULE }} --duration 300
          sarif-output: sarif

      - name: Start ROUNDTRIP analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.ROUNDTRIP }} --duration 300
          sarif-output: sarif

      - name: Start TEXT-LEXER analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.TEXT-LEXER }} --duration 300
          sarif-output: sarif

      - name: Start TEXT-PARSER analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.TEXT-PARSER }} --duration 300
          sarif-output: sarif

      - name: Start VALIDATE-ENSURE-TERMINATION analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.VALIDATE-ENSURE-TERMINATION }} --duration 300
          sarif-output: sarif

      - name: Start VALIDATE-VALID-MODULE analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.VALIDATE-VALID-MODULE }} --duration 300
          sarif-output: sarif

      - name: Start VALIDATE analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.VALIDATE }} --duration 300
          sarif-output: sarif

      - name: Upload SARIF file(s)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif
